[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.22" }
tokio = { version = "1.33.0", features = ["full"] }

[package.metadata.cross.target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile"
